version: 2.1

orbs:
  tfc: cgriggs01/tfc-demo@dev:0d7306c

jobs:
  run-plan:
    docker:
      - image: circleci/golang:1.14.0
    steps:
      - checkout
      - tfc/run-plan

workflows:
  test:
    jobs:
      - run-plan
